05-orm-with-view/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update')
    # 삭제 수정은 조회를 먼저 해야 함. 조회에는 번호가 필요하다.
]

05-orm-with-view/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

05-orm-with-view/articles/views.py
from django.shortcuts import render, redirect
from .models import Article


# 메인 페이지를 응답하는 함수 (+ 전체 게시글 목록)
def index(request):
    # DB에 전체 게시글 요청 후 가져오기
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

# 특정 단일 게시글의 상세 페이지를 응답
# + 단일 게시글 조회
def detail(request, pk):
    # pk로 들어온 정수 값을 활용해 DB id가 pk인 게시글 조회 요청
    article = Article.objects.get(pk=pk)
    # print(article)
    context = {
        'article':article,
    }
    return render(request, 'articles/detail.html', context)

# 게시글을 작성하기 위한 페이지(form)을 제공하는 함수
def new(request):
    return render(request, 'articles/new.html')

# 사용자에게 데이터를 받아 저장하고 페이지를 응답(제공)하는 함수(할일이 많다)
def create(request):
    # 사용자에게 받은 데이터를 추출해야 함
    # request 안에 사용자 입력 데이터 있음
    # print(request.GET)
    # <QueryDict: {'title': ['싸피'], 'content': ['파이썬']}>
    title = request.POST.get('title')
    content = request.POST.get('content')

    # DB에 저장 요청
    # 1. 인스턴스 생성 후 
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()  # 제일 중요

    # # 2. 인스턴스 생성하면서 변수 입력 후 save()
    article = Article(title=title, content=content)
    # 유효성 검사를 하기 위해서는 2번을 추천!
    article.save()

    # # 3. 바로 쿼리셋을 사용해서 생성. save 필요 없음
    # Article.objects.create(title=title, content=content)
    
    # 포스트는 데이터 조작이라 페이지를 응답할 필요가 없다.
    return redirect('articles:detail', article.pk)

def delete(request, pk):
    # 어떤 게시글을 지우는지 먼저 조회
    article = Article.objects.get(pk=pk)
    # DB에 삭제 요청
    article.delete()
    return redirect('articles:index')

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article':article,
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)

    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    
    return redirect('articles:detail', article.pk)

05-orm-with-view/articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>게시글이 문제없이 작성되었습니다.</h1>
  </body>
</html>

05-orm-with-view/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>DETAIL</h1>
    <h3>{{ article.pk }} 번째 글</h3>
    <hr />
    <p>제목: {{ article.title }}</p>
    <p>내용: {{articel.content }}</p>
    <p>작성일: {{ article.created_at }}</p>
    <p>수정일: {{ article.updated_at }}</p>
    <hr />
    <a href="{% url 'articles:edit' article.pk %}">EDIT</a><br />
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제" />
    </form>
    <a href="{% url 'articles:index' %}">[back]</a>
  </body>
</html>

05-orm-with-view/articles/templates/articles/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>EDIT</h1>
    <form action="{% url 'articles:update' article.pk %}" method="POST">
      {% csrf_token %}
      <div>
        <label for="title">Title: </label>
        <input
          type="text"
          name="title"
          id="title"
          value="{{ article.title }}"
        />
      </div>
      <div>
        <label for="content">Content: </label>
        <textarea name="content" id="content">{{ article.content }}</textarea>
      </div>
      <input type="submit" />
    </form>
    <hr />
    <a href="{% url 'articles:index' %}">[back]</a>
  </body>
</html>

05-orm-with-view/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Articles</h1>
    <hr />
    {% for article in articles %}
    <p>글 번호: {{ article.pk }}</p>
    <a href="{% url 'articles:detail' article.pk %}">
      <p>글 제목: {{ article.title }}</p>
    </a>
    <p>글 내용: {{ article.content }}</p>
    <hr />
    {% endfor %}
  </body>
</html>

05-orm-with-view/articles/templates/articles/new.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>NEW</h1>
    <form action="{% url 'articles:create' %}" method="POST">
      {% csrf_token %} {% comment %} POST로 바꾸니 안됨 {% endcomment %}
      <div>
        <label for="title">Title: </label>
        {% comment %} name이 키의 역할을 한다. id는 라벨 태그 때문에. for가
        연결되게 {% endcomment %}
        <input type="text" name="title" id="title" />
      </div>
      <div>
        <label for="content">Content: </label>
        <textarea name="content" id="content"></textarea>
      </div>
      {% comment %} submit이 있어야 제출된다. {% endcomment %}
      <input type="submit" />
    </form>
    <hr />
    <a href="{% url 'articles:index' %}">[back]</a>
  </body>
</html>